#include <GL/glew.h> 
#include <iostream>
#include <fstream>
#include <string>
#include <sstream>
#include "Application.h"

Application::Application()
    : mShader{0}, mIncrement{0.05f}, mUniformLoc{0}, mVBO{0}, mIBO{0}, mVAO{0}
{

}

void Application::GLClearError()
{
    // glGetError() will "pop" the last error off the "error queue"
    while (glGetError() != GL_NO_ERROR);
}

bool Application::GLLogCall(const char* function, const char* file, int line)
{
    // glDebugMessageCallback() is much better way of handling errors in OpenGL
    // GLenum is what glGetError() returns, which is equal to an 'unsigned int'
    while (GLenum error = glGetError())
    {
        std::cout << "[OpenGL Error] (" << error << "): " << function << " " << file << " - line:" << line << std::endl;
        return false;
    }

    return true;
}

Application::ShaderProgramSource Application::ParseShader(const std::string& filepath)
{
    ShaderProgramSource::ShaderType type = ShaderProgramSource::ShaderType::NONE;
    std::ifstream stream(filepath); // The content of the file we read
    std::string line;               // Will contain what word we currently are reading
    std::stringstream ss[2];        // Will contain the "extracted" source code
    while (getline(stream, line))   // While there is more to read, and then fill up 'line' with current word
    {
        if (line.find("#shader") != std::string::npos)
        {
            if (line.find("vertex") != std::string::npos)
                type = ShaderProgramSource::ShaderType::VERTEX;
            else if (line.find("fragment") != std::string::npos)
                type = ShaderProgramSource::ShaderType::FRAGMENT;
        }
        else
        {
            ss[(int)type] << line << '\n';
        }
    }

    // Will return an object of two components. 
    // The default operator overload for '=' will assign these correctly in the ShaderProgramSource struct.
    return {ss[(int)ShaderProgramSource::ShaderType::VERTEX].str(), ss[(int)ShaderProgramSource::ShaderType::FRAGMENT].str()};
}

unsigned int Application::CompileShader(unsigned int type, const std::string& source)
{
    // Creates an empty shader object.
    unsigned int id = glCreateShader(type);

    // source.c_str() = &source[0]
    const char* src = source.c_str();

    // Sets the source code for the 'id' shader (will replace all previous source code).
    // @shader - specifies the shader
    // @count  - specifies the number of elements in the input string
    // @string - a pointer to the actual input string
    // @length - specifies an array of string lengths (?)
    CALL(glShaderSource(id, 1, &src, nullptr));

    // Compiles a shader object
    CALL(glCompileShader(id));

    // Checks if shader was created succesfully.
    int result;
    CALL(glGetShaderiv(id, GL_COMPILE_STATUS, &result));
    if (result == GL_FALSE) // 'GL_FALSE' = 0
    {
        int length;
        CALL(glGetShaderiv(id, GL_INFO_LOG_LENGTH, &length));
        // 'alloca' = Most compilers come with this function. Dynamically allocates memory on the stack.
        char* message = (char*)_malloca(length * sizeof(char));
        CALL(glGetShaderInfoLog(id, length, &length, message));
        std::cout << "Failed to compile " << (type == GL_VERTEX_SHADER ? "vertex" : "fragment")
                                         << " shader!" << std::endl;
        std::cout << message << std::endl;
        CALL(glDeleteShader(id));
        return 0;
    }

    return id;
}

unsigned int Application::CreateShader(const std::string& vertexShader, const std::string& fragmentShader)
{
    // Creates an empty program object
    unsigned int program = glCreateProgram();
    unsigned int vs = CompileShader(GL_VERTEX_SHADER, vertexShader);
    unsigned int fs = CompileShader(GL_FRAGMENT_SHADER, fragmentShader);

    // Attaches a shader object to a program object. I.e. it puts the puzzle pieces together.
    CALL(glAttachShader(program, vs));
    CALL(glAttachShader(program, fs));

    // Will link the program. Any shaders that are attached will take part in
    // this linking proccess. Will create executables. Can be thought of as compiling the program.
    CALL(glLinkProgram(program));

    // Checks to see whether the executables contained in 'program' can actually execute.
    // The information generated by the validation process will be stored in the program's information log.
    CALL(glValidateProgram(program));

    // We are done using the initial shaders (are now "compiled" into the program), so we can delete them. 
    // This will not delete the source code though, so it can be used later for debugging purposes.
    // 'glDetachShader()' is used to delete the actual source code.
    CALL(glDeleteShader(vs));
    CALL(glDeleteShader(fs));

    return program;
}

void Application::init()
{
    // Vertex buffer
    float positions[] = {
        -0.5f, -0.5f, // 0
         0.5f, -0.5f, // 1
         0.5f,  0.5f, // 2
        -0.5f,  0.5f, // 3
    };

    // Index buffer
    unsigned int indices[] = {
        0, 1, 2,
        2, 3, 0
    };

    // --- VERTEX ARRAY ---
    CALL(glGenVertexArrays(1, &mVAO));
    CALL(glBindVertexArray(mVAO));

    // --- VERTEX BUFFER ---
    CALL(glGenBuffers(1, &mVBO));              // Generate '1' buffer with an ID of 'bufferId'
    CALL(glBindBuffer(GL_ARRAY_BUFFER, mVBO)); // "Place" this buffer at the 'GL_ARRAY_BUFFER' slot (used by vertex buffers)

    // Fill up buffer bound at slot 'GL_ARRAY_BUFFER' with the contents of 'positions'.
    CALL(glBufferData(GL_ARRAY_BUFFER, 4 * 2 * sizeof(float), positions, GL_STATIC_DRAW));

    // Enables the attribute at index 0. Disabled attributes will not be used during redering (default)!
    CALL(glEnableVertexAttribArray(0));  

    // Tells the GPU how to interpret the data stored in the selected buffer.
    // This information is stored in the current Vertex Array Object (VAO),
    // so it's THIS function that links/connects the buffer stored at 'GL_ARRAY_BUFFER' (VBO) with the current VAO.
    // The function defines only one attribute in the vertex!
    // @index      - The attribute you are defining.
    //               E.g. 0 = position, 1 = color and 2 = UV.
    // @size       - How many objects define this attribute? (not bytes)
    //               E.g. '3' for a 3D vector containing 3 floats.
    // @type       - The type of data the attribute consists of.
    // @normalized - If you want OpenGL to normalize the value for you.
    //               E.g. normalize a (0 - 255) value into a (0 - 1) value.
    // @stride     - The total size of a whole vertex (in bytes).
    //               E.g. a vertex made up of 3 attributes:
    //               position, color and UV = 12 + 8 + 8 = 28 bytes. 
    // @pointer    - Offset from the start of the vertex to current attribute (in bytes).
    //               E.g. '20' if we were defining a UV attribute where there are
    //               first 12 bytes of position attribute and then 8 bytes of color attribute.
    //               Just remember to cast it like this: (const void*)20 
    CALL(glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, sizeof(float) * 2, 0));

    // --- INDEX BUFFER ---
    CALL(glGenBuffers(1, &mIBO));

    // Bind the buffer at the 'GL_ELEMENT_ARRAY_BUFFER' slot (which is used for index buffers)
    CALL(glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, mIBO)); 
    CALL(glBufferData(GL_ELEMENT_ARRAY_BUFFER, 6 * sizeof(unsigned int), indices, GL_STATIC_DRAW));

    // --- SHADERS ---
    // Fill up 'source' with the source code of the shaders.
    // Written in the OpenGL Shading Language (GLSL). The source code explained:
    // @layout(location = 0) - sets the 'position' variable equal to the attribute you have specified
    //                         at index 0 in your vertex buffer (in this case, the position attribute).
    //                         'position' has to be of type vec4, so it casts it implicitly.
    ShaderProgramSource source = ParseShader("res/shaders/Basic.shader");
    mShader = CreateShader(source.VertexSource, source.FragmentSource);
    CALL(glUseProgram(mShader));

    // --- UNIFORMS ---
    // After binding the program, I send the following values to the shader using a uniform.
    CALL(mUniformLoc = glGetUniformLocation(mShader, "u_Color"));
    ASSERT(mUniformLoc != -1); // Just check that it found it.
    CALL(glUniform4f(mUniformLoc, 0.0f, 0.3f, 0.8f, 1.0f)); // ...4f = 4 floats = vec4

    // Unbind everything
    CALL(glBindVertexArray(0));
    CALL(glUseProgram(0));
    CALL(glBindBuffer(GL_ARRAY_BUFFER, 0));
    CALL(glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
}

void Application::render() 
{
    static float r{0.0f};

    CALL(glUseProgram(mShader));
    CALL(glUniform4f(mUniformLoc, r, 0.3f, 0.8f, 1.0f));

    CALL(glBindVertexArray(mVAO));
    CALL(glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, mIBO));

    // glDrawArrays()   uses the buffer that is bound at slot 'GL_ARRAY_BUFFER'         = Vertex buffer
    // glDrawElements() uses the buffer that is bound at slot 'GL_ELEMENT_ARRAY_BUFFER' = Index buffer
    CALL(glDrawElements(GL_TRIANGLES, 6, GL_UNSIGNED_INT, nullptr));

    // Color cycle calculation
    if (r > 1.0f)
        mIncrement = -0.01f;
    if (r < 0.0f)
        mIncrement =  0.01f;
    r += mIncrement;
}

